"""
Project-wide constants and enumerations.

Kept in one place so magic strings never leak across the codebase.
"""

from __future__ import annotations

from enum import Enum

# Words that address the assistant directly.
WAKE_WORDS: tuple[str, ...] = ("jarvis", "j.a.r.v.i.s", "hey jarvis")

# Default per-provider models, used when none is set explicitly.
DEFAULT_MODELS: dict[str, str] = {
    "anthropic": "claude-sonnet-4-20250514",
    "openai": "gpt-4o",
}

# Default per-provider *fast* models — used for latency-sensitive turns (voice
# replies) when the operator hasn't set LLM_MODEL_FAST. Without this, "use a
# fast model for voice" (see JarvisEngine._ask_llm) silently did nothing unless
# an operator had already opted in, which defeats the point of a speed default.
DEFAULT_FAST_MODELS: dict[str, str] = {
    "anthropic": "claude-3-5-haiku-20241022",
    "openai": "gpt-4o-mini",
}


class Provider(str, Enum):
    """Supported LLM providers."""

    ANTHROPIC = "anthropic"
    OPENAI = "openai"


class Role(str, Enum):
    """Conversation roles."""

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class AssistantState(str, Enum):
    """High-level lifecycle states of the assistant."""

    IDLE = "idle"
    LISTENING = "listening"
    THINKING = "thinking"
    SPEAKING = "speaking"
    EXECUTING = "executing"
    ERROR = "error"


class ResponseType(str, Enum):
    """How a response was produced."""

    LLM = "llm"           # generated by the language model
    SKILL = "skill"       # handled locally by a skill/plugin
    SYSTEM = "system"     # framework-level message (help, errors)
    EMPTY = "empty"       # no actionable content


class EventType(str, Enum):
    """Named events published on the event bus."""

    STARTUP = "startup"
    SHUTDOWN = "shutdown"
    USER_INPUT = "user_input"
    RESPONSE_READY = "response_ready"
    SKILL_MATCHED = "skill_matched"
    SKILL_FAILED = "skill_failed"
    LLM_REQUEST = "llm_request"
    LLM_RESPONSE = "llm_response"
    TOOL_CALL = "tool_call"
    TOOL_RESULT = "tool_result"
    INTEGRATION_CONNECTED = "integration_connected"
    INTEGRATION_ERROR = "integration_error"
    STATE_CHANGED = "state_changed"
    ERROR = "error"
