"""
Telegram interface for J.A.R.V.I.S.

Each Telegram user gets their own persistent session (``tg-<user_id>``), so the
memory subsystem gives every user independent history and recall. The bot is a
thin adapter over :class:`~jarvis.core.engine.JarvisEngine`; the conversational
logic lives in the engine, not here.

Features: a localized command menu, an inline language picker (English /
Russian / Uzbek), HTML-formatted UI, and per-user language that the assistant
replies in.

Run it with:

    python -m jarvis.interfaces.telegram_bot     # or: jarvis-bot

``aiogram`` is an optional dependency, imported lazily so the rest of the
package works without it.
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path

from jarvis.config.settings import Settings, get_settings
from jarvis.core.engine import JarvisEngine
from jarvis.i18n import (
    DEFAULT_LOCALE,
    SUPPORTED_LOCALES,
    normalize_locale,
    t,
)
from jarvis.interfaces.user_prefs import UserPreferences
from jarvis.utils.exceptions import ConfigError, JarvisError
from jarvis.utils.logger import get_logger, setup_logging
from jarvis.voice import VoiceService

logger = get_logger(__name__)

# Telegram hard-caps messages at 4096 characters.
_TELEGRAM_MAX = 4096

# Static banner shown on the Tariffs screen (generated by scripts/gen_plan_banner.py).
_PLANS_BANNER = Path(__file__).parent / "assets" / "plans_banner.png"

# Reconnect backoff for the always-on polling loop (seconds).
_POLL_BACKOFF_INITIAL = 3.0
_POLL_BACKOFF_MAX = 300.0

# Labels for the language-picker buttons (shown in each language natively).
_LANGUAGE_LABELS = {
    "en": "🇬🇧 English",
    "ru": "🇷🇺 Русский",
    "uz": "🇺🇿 O'zbek",
}


def session_id_for(user_id: int) -> str:
    """Stable per-user session id."""
    return f"tg-{user_id}"


def split_message(text: str, limit: int = _TELEGRAM_MAX) -> list[str]:
    """Split ``text`` into Telegram-sized chunks on line boundaries."""
    text = text or "…"
    if len(text) <= limit:
        return [text]
    chunks: list[str] = []
    current = ""
    for line in text.split("\n"):
        while len(line) > limit:  # a single very long line
            chunks.append(line[:limit])
            line = line[limit:]
        if len(current) + len(line) + 1 > limit:
            chunks.append(current)
            current = line
        else:
            current = f"{current}\n{line}" if current else line
    if current:
        chunks.append(current)
    return chunks


async def generate_reply(engine: JarvisEngine, user_id: int, text: str,
                        locale: str | None = None, *,
                        match_input_language: bool = False,
                        model_profile: str | None = None,
                        model_id: str | None = None,
                        byok: dict | None = None,
                        assistant_name: str | None = None,
                        usage=None,
                        source: str = "cli",
                        plan_images: bool = True,
                        return_metadata: bool = False,
                        ) -> str | tuple[str, dict]:
    """Produce the assistant's reply for a Telegram user (testable core).

    When ``locale`` is given (and ``match_input_language`` is False), the
    assistant is asked to reply in that language. For voice, set
    ``match_input_language=True`` so the reply matches the language the user
    actually spoke, whatever it is. ``model_profile`` picks the user's chosen
    AI. If a ``usage`` store is given, the turn's token count is recorded.

    ``source`` flows onto the engine :class:`Request` (e.g. ``"voice"`` gets a
    faster model / shorter tool-round budget / a "keep it brief" prompt hint —
    see :meth:`JarvisEngine._ask_llm`). ``plan_images`` gates the
    ``generate_image`` tool for this turn. ``return_metadata=True`` returns
    ``(text, metadata)`` instead of bare text, so a caller can pick up
    tool-produced artifacts (e.g. a generated image) — default ``False``
    keeps every existing caller's return type unchanged.
    """
    from jarvis.models.response import Request

    session_id = session_id_for(user_id)
    session = engine.session(session_id)
    if match_input_language:
        session.scratch.pop("language", None)
    elif locale:
        session.scratch["language"] = locale
    if model_profile:
        session.scratch["model_profile"] = model_profile
    elif model_profile == "":  # explicit "Auto" — unpin any earlier model
        session.scratch.pop("model_profile", None)
    if model_id:
        session.scratch["model_id"] = model_id
    else:
        session.scratch.pop("model_id", None)
    if assistant_name:
        session.scratch["assistant_name"] = assistant_name
    else:
        session.scratch.pop("assistant_name", None)
    if byok:
        session.scratch["byok"] = byok
    else:
        session.scratch.pop("byok", None)
    session.scratch["plan_images"] = plan_images
    try:
        response = await engine.process(
            Request(text=text, session_id=session_id, source=source))
        if usage is not None:
            usage.record(user_id, tokens=response.tokens)
        if return_metadata:
            return response.text, response.metadata
        return response.text
    except JarvisError as exc:
        logger.error("Reply failed for user %s: %s", user_id, exc)
        error_text = t("error", locale, error=str(exc))
        return (error_text, {}) if return_metadata else error_text


async def with_typing(bot, chat_id, coro):
    """Await ``coro`` while keeping Telegram's "typing…" indicator alive.

    A single chat action lasts ~5s, so a long reply looks frozen. Re-send it
    every few seconds until the reply is ready — the user always sees activity.
    """
    from aiogram.enums import ChatAction

    async def _ping() -> None:
        while True:
            try:
                await bot.send_chat_action(chat_id, ChatAction.TYPING)
            except Exception:  # noqa: BLE001 - never let the pinger crash the reply
                pass
            await asyncio.sleep(4.0)

    pinger = asyncio.create_task(_ping())
    try:
        return await coro
    finally:
        pinger.cancel()


def _is_allowed(settings: Settings, user_id: int) -> bool:
    allowlist = settings.telegram_allowlist()
    return not allowlist or user_id in allowlist


def handle_successful_payment(billing, settings: Settings, telegram_user_id: int,
                            charge_id: str, locale: str, *,
                            amount: int = 0, currency: str = "",
                            plan: str | None = None) -> str:
    """Fulfil a paid Telegram invoice and return the reply text (testable core).

    ``plan`` overrides the licence plan name (e.g. a purchased tier "plus" /
    "pro"); when ``None`` the server's default ``billing_plan`` is used.
    """
    days = settings.billing_plan_days or None
    fulfillment = billing.process_payment(
        charge_id,
        telegram_user_id=telegram_user_id,
        plan=plan or settings.billing_plan,
        valid_days=days,
        amount=amount,
        currency=currency,
    )
    if fulfillment is None:  # duplicate delivery of the same charge
        return t("buy_thanks_existing", locale, username="—")
    if fulfillment.created_account:
        return t("buy_thanks_new", locale, username=fulfillment.username,
                password=fulfillment.password)
    return t("buy_thanks_existing", locale, username=fulfillment.username)


def handle_link(service, text: str, telegram_user_id: int, locale: str) -> str:
    """Process ``/link <code>`` and return the reply text (testable core).

    ``service`` is a :class:`~jarvis.licensing.service.LicenseService` or
    ``None`` when accounts are disabled on this server.
    """
    if service is None:
        return t("link_disabled", locale)
    parts = (text or "").split(maxsplit=1)
    code = parts[1].strip() if len(parts) > 1 else ""
    if not code:
        return t("link_usage", locale)
    account = service.confirm_pairing(code, telegram_user_id)
    if account is None:
        return t("link_invalid", locale)
    return t("link_success", locale, username=account.username)


def _resolve_locale(prefs: UserPreferences, user) -> str:
    """User's stored language, else a guess from their Telegram client."""
    stored = prefs.get_language(user.id)
    if stored:
        return stored
    return normalize_locale(getattr(user, "language_code", None))


async def run(settings: Settings | None = None) -> None:
    """Start the Telegram bot (long-polling)."""
    settings = settings or get_settings()
    setup_logging(level=settings.log_level, log_file=settings.log_file)

    if not settings.telegram_bot_token:
        raise ConfigError(
            "TELEGRAM_BOT_TOKEN is not set. Add it to your .env file "
            "(get a token from @BotFather)."
        )

    try:
        from aiogram import Bot, Dispatcher, F
        from aiogram.client.default import DefaultBotProperties
        from aiogram.enums import ChatAction, ParseMode
        from aiogram.filters import Command, CommandStart
        from aiogram.types import (
            BotCommand,
            BufferedInputFile,
            CallbackQuery,
            InlineKeyboardButton,
            InlineKeyboardMarkup,
            Message,
        )
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise ConfigError(
            "The 'aiogram' package is required for the Telegram bot. "
            "Install it with: pip install aiogram"
        ) from exc

    engine = JarvisEngine(settings)
    await engine.start()
    prefs = UserPreferences(settings.memory_db_path)
    voice = VoiceService.from_settings(settings) if settings.voice_enabled else None
    image_service = None
    if settings.image_enabled:
        from jarvis.media import ImageService
        image_service = ImageService.from_settings(settings)
        if not image_service.available():
            image_service = None
    license_service = None
    if settings.auth_enabled:
        from jarvis.licensing import LicenseService
        license_service = LicenseService(
            settings.auth_db_path, token_ttl_hours=settings.auth_token_ttl_hours
        )
    billing = None
    if settings.billing_enabled and license_service is not None:
        from jarvis.billing import BillingService
        billing = BillingService(license_service, settings.auth_db_path)
    from jarvis.interfaces.usage import UsageStore
    usage = UsageStore(settings.memory_db_path)
    from jarvis.interfaces.referrals import ReferralStore
    referrals = ReferralStore(settings.memory_db_path)
    from jarvis.interfaces.model_search import ModelIndex
    model_index = ModelIndex(settings.openrouter_base_url)
    from jarvis.interfaces.reminders import ReminderStore
    reminder_store = ReminderStore(settings.memory_db_path)
    from jarvis.interfaces.automations import AutomationStore
    automation_store = AutomationStore(settings.memory_db_path)
    from jarvis.interfaces.user_integrations import UserIntegrationsStore
    user_int_store = UserIntegrationsStore(settings.memory_db_path)
    from jarvis.interfaces.model_registry import FavoritesStore
    favorites = FavoritesStore(settings.memory_db_path)
    #: Filled in at startup once we know the bot's @username (for invite links).
    bot_username = ""

    from jarvis.billing import PRO, build_plans, resolve_plan
    plans = build_plans(
        free_daily=settings.plan_free_daily,
        plus_daily=settings.plan_plus_daily,
        pro_daily=settings.plan_pro_daily,
        plus_price=settings.plan_plus_price_stars,
        pro_price=settings.plan_pro_price_stars,
    )

    def _user_plan(user_id: int):
        """Resolve a user's tier: admins, VIPs and unrestricted deployments are
        Pro; otherwise it's the plan on their active licence, else Free."""
        if (license_service is None or user_id in settings.telegram_admins()
                or user_id in settings.telegram_vips()):
            return plans[PRO]
        account = license_service.get_account_by_telegram(user_id)
        if account is None:
            return plans["free"]
        import time as _time
        active = next((lic for lic in license_service.list_licenses(account.id)
                    if lic.is_valid(now=_time.time())), None)
        return resolve_plan(active.plan, plans) if active else plans["free"]

    bot = Bot(
        token=settings.telegram_bot_token,
        default=DefaultBotProperties(parse_mode=ParseMode.HTML),
    )
    dp = Dispatcher()

    def _language_keyboard() -> "InlineKeyboardMarkup":
        return InlineKeyboardMarkup(inline_keyboard=[[
            InlineKeyboardButton(text=_LANGUAGE_LABELS[loc], callback_data=f"lang:{loc}")
            for loc in SUPPORTED_LOCALES
        ]])

    def _button(label: str, data: str) -> "InlineKeyboardButton":
        # A "data" that looks like a URL becomes a link button, else a callback.
        if data.startswith("http"):
            return InlineKeyboardButton(text=label, url=data)
        return InlineKeyboardButton(text=label, callback_data=data)

    def _markup(rows) -> "InlineKeyboardMarkup":
        return InlineKeyboardMarkup(inline_keyboard=[
            [_button(label, data) for label, data in row] for row in rows
        ])

    def _main_screen(user_id: int, locale: str):
        from jarvis.interfaces.bot_menu import screen_main
        return screen_main(
            locale,
            is_admin=user_id in settings.telegram_admins(),
            billing_on=billing is not None,
            accounts_on=license_service is not None,
            multi_model=len(engine.llm.list_profiles()) > 1,
            voice_on=voice is not None and voice.stt_available(),
            channel=settings.telegram_channel,
            name=settings.user_name,
            plan=_user_plan(user_id) if billing is not None else None,
            used_today=usage.stats(user_id)["messages_today"],
            image_on=image_service is not None,
            referral_on=bool(bot_username),
            integrations_on=settings.integrations_enabled,
            assistant_name=(prefs.get_assistant_name(user_id)
                            or settings.assistant_name),
        )

    async def _is_subscribed(user_id: int) -> bool:
        """True if the user is in the required channel (or none is configured)."""
        channel = settings.telegram_required_channel
        if not channel:
            return True
        try:
            member = await bot.get_chat_member(channel, user_id)
            return member.status not in ("left", "kicked")
        except Exception as exc:  # noqa: BLE001 - treat lookup errors as blocked
            logger.debug("Subscription check failed for %s: %s", user_id, exc)
            return False

    async def _show_gate(message: "Message", locale: str) -> None:
        from jarvis.interfaces.bot_menu import gate_screen
        text, rows = gate_screen(locale, settings.telegram_required_channel)
        await message.answer(text, reply_markup=_markup(rows))

    async def _guard(message: "Message", locale: str) -> bool:
        if _is_allowed(settings, message.from_user.id):
            return True
        await message.answer(t("not_authorized", locale))
        return False

    async def _open_menu(message: "Message", user_id: int, locale: str) -> None:
        text, rows = _main_screen(user_id, locale)
        await message.answer(text, reply_markup=_markup(rows))

    async def _within_limit(message: "Message", user_id: int, locale: str) -> bool:
        """Enforce the daily message allowance. Returns True if the turn is
        allowed; otherwise shows the limit screen and returns False. Only
        applies when billing is on (otherwise everyone is effectively Pro)."""
        if billing is None:
            return True
        # BYOK users pay their own provider — no daily cap.
        if prefs.get_byok(user_id):
            return True
        plan = _user_plan(user_id)
        used_today = usage.stats(user_id)["messages_today"]
        if plan.unlimited:
            return True
        # Referral bonus extends the daily allowance.
        bonus = referrals.count(user_id) * settings.referral_bonus_daily
        if used_today < plan.daily_messages + bonus:
            return True
        from jarvis.interfaces.bot_menu import limit_screen
        text, rows = limit_screen(locale, plan)
        await message.answer(text, reply_markup=_markup(rows))
        return False

    async def _make_image(message: "Message", prompt: str, locale: str) -> None:
        """Generate an image from ``prompt`` and send it back."""
        if image_service is None:
            await message.answer(t("image_locked", locale))
            return
        from aiogram.enums import ChatAction as _CA
        from aiogram.types import BufferedInputFile
        await message.bot.send_chat_action(message.chat.id, _CA.UPLOAD_PHOTO)
        await message.answer(t("image_generating", locale))
        try:
            png = await image_service.generate(prompt)
        except Exception as exc:  # noqa: BLE001 - surface a clean error
            logger.error("Image generation failed: %s", exc)
            await message.answer(t("image_failed", locale, error=str(exc)),
                                parse_mode=None)
            return
        usage.record(message.from_user.id, tokens=0)  # counts toward the daily limit
        await message.answer_photo(
            BufferedInputFile(png, "jarvis.png"), caption=f"🎨 {prompt[:900]}")

    async def _run_prompt(message: "Message", user_id: int, prompt: str,
                        locale: str) -> None:
        """Send ``prompt`` to the engine as if the user typed it (used by Ideas)."""
        if not await _within_limit(message, user_id, locale):
            return
        await message.bot.send_chat_action(message.chat.id, ChatAction.TYPING)
        reply = await generate_reply(
            engine, user_id, prompt, locale,
            model_profile=prefs.get_model(user_id),
            model_id=prefs.get_model_id(user_id),
            byok=prefs.get_byok(user_id),
            assistant_name=prefs.get_assistant_name(user_id), usage=usage)
        for chunk in split_message(reply):
            await message.answer(chunk, parse_mode=None)

    async def _handle_reminder(message: "Message", locale: str) -> None:
        """Parse and store a 'remind me …' request."""
        from datetime import datetime

        from jarvis.interfaces.reminders import parse_reminder
        parsed = parse_reminder(message.text, datetime.now())
        if parsed is None:
            await message.answer(t("reminder_bad", locale), parse_mode=None)
            return
        due, body = parsed
        reminder_store.add(message.from_user.id, message.chat.id,
                        body or t("reminders_title", locale), due.timestamp())
        when = due.strftime("%d.%m %H:%M")
        await message.answer(t("reminder_set", locale, when=when), parse_mode=None)

    async def _handle_automation(message: "Message", locale: str) -> None:
        """Parse and store a recurring 'каждый …' task."""
        from datetime import datetime

        from jarvis.interfaces.automations import next_run, parse_automation
        spec = parse_automation(message.text, datetime.now())
        if spec is None or not spec.prompt:
            await message.answer(t("auto_bad", locale), parse_mode=None)
            return
        when = next_run(spec, datetime.now())
        automation_store.add(message.from_user.id, message.chat.id, spec, when)
        nxt = datetime.fromtimestamp(when).strftime("%d.%m %H:%M")
        await message.answer(t("auto_set", locale, when=nxt), parse_mode=None)

    def _automation_items(user_id: int) -> list:
        from datetime import datetime
        items = []
        for a in automation_store.list_active(user_id):
            nxt = datetime.fromtimestamp(a["next_ts"]).strftime("%d.%m %H:%M")
            items.append((a["id"], f"{a['prompt'][:34]} · ⏭ {nxt}"))
        return items

    def _integrations_screen(user_id: int, locale: str):
        import jarvis.interfaces.bot_menu as bm
        from jarvis.interfaces.user_integrations import (
            KINDS,
            integration_limit_reached,
        )
        plan = _user_plan(user_id)
        count = user_int_store.count(user_id)
        limit = (t("plan_unlimited", locale)
                if getattr(plan, "unlimited_integrations", False)
                else str(plan.integrations))
        items = [(i.id, f"{KINDS.get(i.kind, i.kind)} · {i.label}"[:44])
                for i in user_int_store.list(user_id)]
        return bm.screen_user_integrations(
            locale, items, count, limit,
            at_limit=integration_limit_reached(plan, count))

    async def _send_support(message: "Message", locale: str) -> None:
        """Forward a user's support message to the bot owner(s)."""
        admins = settings.telegram_admins()
        if not admins:
            await message.answer(t("support_disabled", locale))
            return
        u = message.from_user
        header = f"📩 Support from <code>{u.id}</code>"
        if u.username:
            header += f" (@{u.username})"
        for admin_id in admins:
            try:
                await message.bot.send_message(admin_id, header)
                await message.bot.forward_message(
                    admin_id, message.chat.id, message.message_id)
            except Exception as exc:  # noqa: BLE001 - admin unreachable
                logger.debug("Support forward to %s failed: %s", admin_id, exc)
        await message.answer(t("support_sent", locale))

    async def _save_byok(message: "Message", provider: str, key: str,
                        locale: str) -> None:
        """Store the user's own provider key (removes their limits)."""
        key = (key or "").strip()
        if len(key) < 12 or " " in key:
            await message.answer(t("byok_bad", locale), parse_mode=None)
            engine.session(session_id_for(message.from_user.id)
                        ).scratch["awaiting_byok"] = provider
            return
        from jarvis.config.constants import DEFAULT_MODELS
        model = {
            "openai": DEFAULT_MODELS.get("openai", ""),
            "anthropic": DEFAULT_MODELS.get("anthropic", ""),
            "openrouter": settings.openrouter_model,
        }.get(provider, "")
        prefs.set_byok(message.from_user.id, provider, key, model)
        engine.session(session_id_for(message.from_user.id)).scratch["byok"] = {
            "provider": provider, "key": key, "model": model}
        await message.answer(t("byok_saved", locale))
        # Best effort: strip the key from the chat (works only where allowed).
        try:
            await message.delete()
        except Exception:  # noqa: BLE001
            pass

    async def _save_integration(message: "Message", kind: str,
                                locale: str) -> None:
        """Validate + store a user's own integration, enforcing the tier limit."""
        from jarvis.interfaces.user_integrations import (
            integration_limit_reached,
            validate,
        )
        user_id = message.from_user.id
        # Re-check the limit at save time (plan may have changed).
        if integration_limit_reached(_user_plan(user_id),
                                    user_int_store.count(user_id)):
            await message.answer(t("uint_limit", locale))
            return
        text = (message.text or "").strip()
        if kind == "homeassistant":
            # Expect "https://ha.local | LONG_LIVED_TOKEN".
            parts_ = [p.strip() for p in re.split(r"[|\n]", text, maxsplit=1)]
            if len(parts_) != 2:
                await message.answer(t("uint_ask_ha", locale))
                engine.session(session_id_for(user_id)
                            ).scratch["awaiting_integration"] = kind
                return
            config = {"url": parts_[0], "token": parts_[1]}
            label = parts_[0]
        else:
            config = {"url": text}
            label = text
        ok, detail = await validate(kind, config)
        if not ok:
            await message.answer(t("uint_bad", locale, detail=detail))
            return
        user_int_store.add(user_id, kind, label[:60], config)
        await message.answer(t("uint_saved", locale))
        try:
            await message.delete()  # the token may be in the message
        except Exception:  # noqa: BLE001
            pass

    async def _handle_api_command(message: "Message", parsed, locale: str) -> None:
        """Handle an in-chat ``api`` command: connect a key or search models."""
        import jarvis.interfaces.bot_menu as bm
        kind, a, b = parsed
        user_id = message.from_user.id
        if kind == "help":
            await message.answer(t("api_help", locale))
            return
        if kind == "key":
            await _save_byok(message, a, b, locale)
            return
        # kind == "search"
        results = await model_index.search(a, limit=8)
        engine.session(session_id_for(user_id)).scratch["search_results"] = [
            m.slug for m in results]
        text, rows = bm.screen_search(
            locale, results, prefs.get_model_id(user_id) or "")
        if results and not _openrouter_available(user_id):
            text += "\n\n" + t("search_need_or", locale)
        await message.answer(text, reply_markup=_markup(rows))

    @dp.message(CommandStart())
    async def _start(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        prefs.touch(message.from_user.id, message.chat.id)
        # Deep-link referral payload: "/start ref_<referrer_id>".
        payload = (message.text or "").split(maxsplit=1)
        if len(payload) > 1 and payload[1].startswith("ref_"):
            ref = payload[1][4:]
            if ref.isdigit():
                referrals.record(ref, message.from_user.id)
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        if prefs.get_language(message.from_user.id) is None:
            await message.answer(t("choose_language", locale),
                                reply_markup=_language_keyboard())
        else:
            await _open_menu(message, message.from_user.id, locale)

    def _profile_message(user, locale: str) -> str:
        from jarvis.interfaces.bot_menu import profile_text
        account, verified = None, False
        if license_service is not None:
            acc = license_service.get_account_by_telegram(user.id)
            if acc is not None:
                account, verified = acc.username, acc.telegram_verified
        byok = prefs.get_byok(user.id)
        return profile_text(
            locale, telegram_id=user.id,
            name=user.full_name or user.username or "—",
            language=locale, model=prefs.get_model(user.id) or "",
            account=account, telegram_verified=verified,
            stats=usage.stats(user.id),
            plan_label=t(f"plan_{_user_plan(user.id).name}", locale)
            if billing is not None else None,
            voice_on=voice is not None and voice.stt_available(),
            images_on=image_service is not None,
            own_key=(byok or {}).get("provider", ""),
        )

    async def _edit(callback: "CallbackQuery", text: str, rows) -> None:
        """Edit the menu message in place (fall back to a new message).

        A photo message (the Tariffs banner) can't be turned back into a text
        message by editing, so it's deleted and replaced with a fresh one.
        """
        msg = callback.message
        if getattr(msg, "photo", None):
            try:
                await msg.delete()
            except Exception:  # noqa: BLE001
                pass
            await msg.answer(text, reply_markup=_markup(rows))
            return
        try:
            await msg.edit_text(text, reply_markup=_markup(rows))
        except Exception:  # noqa: BLE001 - message unchanged / too old
            await msg.answer(text, reply_markup=_markup(rows))

    def _openrouter_available(user_id: int) -> bool:
        """OpenRouter is usable if the server has it, or the user brought a key."""
        if "openrouter" in engine.llm.list_profiles():
            return True
        return (prefs.get_byok(user_id) or {}).get("provider") == "openrouter"

    def _settings_screen(loc: str, user_id: int):
        from jarvis.interfaces.bot_menu import screen_settings
        return screen_settings(loc,
                            search_on=settings.search_enabled,
                            mcp_on=engine.mcp is not None)

    def _settings_ai(loc: str, user_id: int):
        from jarvis.interfaces.bot_menu import screen_settings_ai
        profiles = engine.llm.list_profiles()
        return screen_settings_ai(loc, multi_model=len(profiles) > 1,
                                catalog_on=_openrouter_available(user_id))

    def _settings_tools(loc: str):
        from jarvis.interfaces.bot_menu import screen_settings_tools
        return screen_settings_tools(loc, search_on=settings.search_enabled,
                                    mcp_on=engine.mcp is not None)

    def _settings_prefs(loc: str, user_id: int):
        from jarvis.interfaces.bot_menu import screen_settings_prefs
        return screen_settings_prefs(loc, proactive=prefs.get_proactive(user_id))

    def _reminder_items(user_id: int) -> list:
        from datetime import datetime
        items = []
        for r in reminder_store.list_active(user_id):
            when = datetime.fromtimestamp(r["due_ts"]).strftime("%d.%m %H:%M")
            items.append((r["id"], f"{when} — {r['text']}"))
        return items

    async def _market_cb(callback: "CallbackQuery", action: str, parts,
                        locale: str) -> None:
        """Model marketplace: hub, lists, categories, providers, cards, compare."""
        import jarvis.interfaces.bot_menu as bm
        import jarvis.interfaces.model_registry as mr
        user = callback.from_user
        favs = [c.slug for c in favorites.list(user.id)]
        current = prefs.get_model_id(user.id) or ""

        def show_list(title, cards):
            return bm.screen_market_list(locale, title, cards, current, favs)

        if action == "market":
            await _edit(callback, *bm.screen_market_hub(locale))
        elif action == "mktsearch":
            engine.session(session_id_for(user.id)
                        ).scratch["awaiting_market_search"] = True
            await callback.message.answer(t("market_search_ask", locale))
        elif action == "mktpop":
            await _edit(callback, *show_list(t("market_popular", locale), mr.popular()))
        elif action == "mktfree":
            await _edit(callback, *show_list(t("market_free", locale),
                                            mr.free_models()))
        elif action == "mkttop":
            await _edit(callback, *show_list(t("market_top", locale), mr.top_rated()))
        elif action == "mktfavs":
            await _edit(callback, *show_list(t("market_favs", locale),
                                            favorites.list(user.id)))
        elif action == "mktcats":
            await _edit(callback, *bm.screen_categories(locale))
        elif action == "mktprovs":
            await _edit(callback, *bm.screen_providers(locale))
        elif action == "mktcat":
            cid = parts[2]
            label = mr.CATEGORIES.get(cid, ("", cid))[1]
            await _edit(callback, *show_list(label, mr.by_category(cid)))
        elif action == "mktprov":
            pid = parts[2]
            await _edit(callback, *show_list(mr.PROVIDERS.get(pid, pid),
                                            mr.by_provider(pid)))
        elif action == "mktcard":
            card = mr.at(int(parts[2]))
            if card:
                await _edit(callback, *bm.screen_model_card(
                    locale, card, is_fav=favorites.is_favorite(user.id, card.slug),
                    can_use=_openrouter_available(user.id)))
        elif action == "mktuse":
            card = mr.at(int(parts[2]))
            if not card:
                return
            if not _openrouter_available(user.id):
                await callback.message.answer(t("search_need_or", locale))
                return
            prefs.set_model_id(user.id, card.slug)
            prefs.set_model(user.id, "")
            sess = engine.session(session_id_for(user.id))
            sess.scratch["model_id"] = card.slug
            sess.scratch.pop("model_profile", None)
            await callback.message.answer(t("model_set", locale, model=card.name))
        elif action == "mktfav":
            card = mr.at(int(parts[2]))
            if card:
                favorites.toggle(user.id, card.slug)
                await _edit(callback, *bm.screen_model_card(
                    locale, card, is_fav=favorites.is_favorite(user.id, card.slug),
                    can_use=_openrouter_available(user.id)))
        elif action == "mktcmpadd":
            card = mr.at(int(parts[2]))
            sess = engine.session(session_id_for(user.id))
            basket = sess.scratch.setdefault("compare", [])
            if card and card.slug not in basket and len(basket) < 4:
                basket.append(card.slug)
            cards = [mr.get(s) for s in basket if mr.get(s)]
            await _edit(callback, *bm.screen_compare(locale, cards))
        elif action == "mktcmp":
            basket = engine.session(session_id_for(user.id)
                                    ).scratch.get("compare", [])
            cards = [mr.get(s) for s in basket if mr.get(s)]
            await _edit(callback, *bm.screen_compare(locale, cards))
        elif action == "mktcmpclear":
            engine.session(session_id_for(user.id)).scratch["compare"] = []
            await _edit(callback, *bm.screen_compare(locale, []))

    async def _show_plans(callback: "CallbackQuery", text: str, rows) -> None:
        """Render the Tariffs screen as a banner photo + caption + buttons."""
        msg = callback.message
        if not _PLANS_BANNER.exists():
            await _edit(callback, text, rows)
            return
        from aiogram.types import FSInputFile
        try:
            await msg.delete()
        except Exception:  # noqa: BLE001
            pass
        try:
            await msg.answer_photo(FSInputFile(str(_PLANS_BANNER)),
                                caption=text, reply_markup=_markup(rows))
        except Exception:  # noqa: BLE001 - fall back to plain text
            await msg.answer(text, reply_markup=_markup(rows))

    @dp.callback_query(F.data.startswith("m:"))
    async def _menu_cb(callback: "CallbackQuery") -> None:
        import jarvis.interfaces.bot_menu as bm
        user = callback.from_user
        locale = _resolve_locale(prefs, user)
        parts = callback.data.split(":")
        action = parts[1]
        back = [[(t("menu_back", locale), "m:main")]]

        # The subscription "I subscribed" button needs its own answer (an alert
        # when the user still isn't in the channel), so it can't share the
        # blanket answer() below — Telegram honours only the first answer.
        if action == "checksub":
            if await _is_subscribed(user.id):
                await callback.answer()
                await _edit(callback, *_main_screen(user.id, locale))
            else:
                await callback.answer(t("gate_not_yet", locale), show_alert=True)
            return

        await callback.answer()

        # Admin-only actions: never trust the callback — re-check the caller.
        if action in ("admin", "adminpanel", "adminsales"):
            if user.id not in settings.telegram_admins():
                return
            if action == "admin":
                await _edit(callback, *bm.screen_admin(
                    locale, billing_on=billing is not None))
            elif license_service is None:
                await _edit(callback, t("admin_needs_auth", locale), back)
            else:
                from jarvis.interfaces.admin_panel import (
                    panel_text, sales_report_text)
                body = (panel_text(license_service, billing,
                                   settings.assistant_name)
                        if action == "adminpanel"
                        else sales_report_text(license_service, billing))
                await _edit(callback, body, back)
            return

        if action == "main":
            await _edit(callback, *_main_screen(user.id, locale))
        elif action == "close":
            # ❌ closes the menu: delete the card, leave a tiny hint.
            try:
                await callback.message.delete()
            except Exception:  # noqa: BLE001
                await _edit(callback, t("menu_closed", locale), [])
            else:
                await callback.message.answer(t("menu_closed", locale))
        elif action == "voice":
            await _edit(callback, *bm.screen_voice(locale))
        elif action == "ideas":
            await _edit(callback, *bm.screen_ideas(locale))
        elif action == "idea":
            prompt = t(bm.IDEA_KEYS[int(parts[2])], locale)
            # Send the example as if the user typed it (strip the leading emoji).
            await _run_prompt(callback.message, user.id, prompt, locale)
        elif action == "newchat":
            await engine.reset(session_id_for(user.id))
            await _edit(callback, t("newchat_done", locale),
                        [[(t("menu_back", locale), "m:main")]])
        elif action == "reminders":
            await _edit(callback, *bm.screen_reminders(
                locale, _reminder_items(user.id)))
        elif action == "remcancel":
            reminder_store.cancel(int(parts[2]), user.id)
            await _edit(callback, *bm.screen_reminders(
                locale, _reminder_items(user.id)))
        elif action == "automations":
            await _edit(callback, *bm.screen_automations(
                locale, _automation_items(user.id)))
        elif action == "autocancel":
            automation_store.cancel(int(parts[2]), user.id)
            await _edit(callback, *bm.screen_automations(
                locale, _automation_items(user.id)))
        elif action == "myint":
            await _edit(callback, *_integrations_screen(user.id, locale))
        elif action == "intadd":
            from jarvis.interfaces.user_integrations import (
                integration_limit_reached,
            )
            if integration_limit_reached(_user_plan(user.id),
                                        user_int_store.count(user.id)):
                await _show_plans(callback, *bm.screen_plans_hub(
                    locale, plans, _user_plan(user.id).name))
                return
            kind = parts[2]
            engine.session(session_id_for(user.id)
                        ).scratch["awaiting_integration"] = kind
            ask = "uint_ask_ha" if kind == "homeassistant" else "uint_ask_hook"
            await callback.message.answer(t(ask, locale))
        elif action == "intdel":
            user_int_store.remove(int(parts[2]), user.id)
            await _edit(callback, *_integrations_screen(user.id, locale))
        elif action == "proactive":
            new_state = not prefs.get_proactive(user.id)
            prefs.set_proactive(user.id, new_state)
            await callback.message.answer(
                t("proactive_on" if new_state else "proactive_off", locale))
            await _edit(callback, *_settings_prefs(locale, user.id))
        elif action == "renamea":
            engine.session(
                session_id_for(user.id)).scratch["awaiting_assistant_name"] = True
            current = prefs.get_assistant_name(user.id) or settings.assistant_name
            await callback.message.answer(
                t("rename_ask", locale, name=current))
        elif action == "support":
            engine.session(session_id_for(user.id)).scratch["awaiting_support"] = True
            await callback.message.answer(t("support_ask", locale))
        elif action == "about":
            from jarvis import __version__
            await _edit(callback, *bm.screen_about(
                locale, version=__version__,
                voice_on=voice is not None and voice.stt_available(),
                images_on=image_service is not None,
                catalog_on=_openrouter_available(user.id),
                billing_on=billing is not None))
        elif action == "settings":
            await _edit(callback, *_settings_screen(locale, user.id))
        elif action == "setai":
            await _edit(callback, *_settings_ai(locale, user.id))
        elif action == "settools":
            await _edit(callback, *_settings_tools(locale))
        elif action == "setprefs":
            await _edit(callback, *_settings_prefs(locale, user.id))
        elif action.startswith("mkt") or action == "market":
            await _market_cb(callback, action, parts, locale)
        elif action == "catalog":
            page = int(parts[2]) if len(parts) > 2 else 0
            await _edit(callback, *bm.screen_catalog(
                locale, _user_plan(user.id).name,
                prefs.get_model_id(user.id) or "", page))
        elif action == "setcat":
            from jarvis.interfaces import model_catalog as mc
            idx = int(parts[2])
            model = mc.CATALOG[idx] if 0 <= idx < len(mc.CATALOG) else None
            if model is None:
                return
            tier = _user_plan(user.id).name
            if not mc.unlocked(model, tier):
                # Locked for this tier — send them to the Tariffs screen.
                await _show_plans(callback, *bm.screen_plans_hub(locale, plans, tier))
                return
            prefs.set_model_id(user.id, model.slug)
            prefs.set_model(user.id, "")  # a specific model supersedes a profile
            sess = engine.session(session_id_for(user.id))
            sess.scratch["model_id"] = model.slug
            sess.scratch.pop("model_profile", None)
            await _edit(callback, *bm.screen_catalog(
                locale, tier, model.slug, idx // mc.PAGE_SIZE))
        elif action == "image":
            # Image generation is a Plus/Pro feature; free users get the upsell.
            plan = _user_plan(user.id)
            if not plan.images:
                await _show_plans(callback, *bm.screen_plans_hub(locale, plans, plan.name))
                return
            engine.session(session_id_for(user.id)).scratch["awaiting_image"] = True
            await callback.message.answer(t("image_ask", locale))
        elif action == "pick":
            idx = int(parts[2])
            slugs = engine.session(session_id_for(user.id)
                                ).scratch.get("search_results", [])
            if not (0 <= idx < len(slugs)):
                return
            if not _openrouter_available(user.id):
                await callback.message.answer(t("search_need_or", locale))
                return
            slug = slugs[idx]
            prefs.set_model_id(user.id, slug)
            prefs.set_model(user.id, "")
            sess = engine.session(session_id_for(user.id))
            sess.scratch["model_id"] = slug
            sess.scratch.pop("model_profile", None)
            await callback.message.answer(t("model_set", locale, model=slug))
        elif action == "referral":
            link = bm.referral_link(bot_username, user.id)
            await _edit(callback, *bm.screen_referral(
                locale, link=link, count=referrals.count(user.id),
                bonus_each=settings.referral_bonus_daily))
        elif action == "searchprov":
            from jarvis.search.manager import SearchManager
            mgr = SearchManager.from_settings(settings)
            await _edit(callback, *bm.screen_search_providers(
                locale, mgr.statuses(), mgr.active()))
        elif action == "mcp":
            from jarvis.mcp.skill import MCPToolSkill
            statuses = engine.mcp.statuses() if engine.mcp else []
            tool_names = [s.name for s in engine.skills.all()
                        if isinstance(s, MCPToolSkill)]
            await _edit(callback, *bm.screen_mcp(locale, statuses, tool_names))
        elif action == "byok":
            current = (prefs.get_byok(user.id) or {}).get("provider")
            await _edit(callback, *bm.screen_byok(locale, current))
        elif action == "byokset":
            provider = parts[2]
            engine.session(session_id_for(user.id)).scratch["awaiting_byok"] = provider
            await callback.message.answer(t("byok_ask", locale))
        elif action == "byokoff":
            prefs.clear_byok(user.id)
            engine.session(session_id_for(user.id)).scratch.pop("byok", None)
            await _edit(callback, t("byok_cleared", locale),
                        [[(t("menu_back", locale), "m:settings")]])
        elif action == "memory":
            await _edit(callback, *bm.screen_memory(locale))
        elif action == "help":
            await _edit(callback, *bm.screen_help(locale))
        elif action == "link":
            await _edit(callback, *bm.screen_link(
                locale, app_login=license_service is not None))
        elif action == "appcode":
            if license_service is None:
                await callback.message.answer(t("app_login_off", locale))
            else:
                code = license_service.create_telegram_login_code(user.id)
                await callback.message.answer(
                    t("app_login_code", locale, code=code), parse_mode=None)
        elif action == "model":
            await _edit(callback, *bm.screen_model(
                locale, engine.llm.list_profiles(), prefs.get_model(user.id) or ""))
        elif action == "language":
            await _edit(callback, *bm.screen_language(locale, locale))
        elif action == "profile":
            await _edit(callback, _profile_message(user, locale),
                        bm.card_rows(locale, "profile"))
        elif action == "usage":
            await _edit(callback, bm.usage_text(locale, usage.stats(user.id)),
                        bm.card_rows(locale, "usage"))
        elif action == "subscription":
            account, lics = None, []
            if license_service is not None:
                acc = license_service.get_account_by_telegram(user.id)
                if acc is not None:
                    account, lics = acc.username, license_service.list_licenses(acc.id)
            await _edit(callback, bm.subscription_text(
                locale, account=account, licenses=lics),
                bm.card_rows(locale, "subscription"))
        elif action == "setmodel":
            choice = parts[2]
            session = engine.session(session_id_for(user.id))
            # Picking a profile supersedes any specific catalog model.
            prefs.set_model_id(user.id, "")
            session.scratch.pop("model_id", None)
            if choice == "auto":
                prefs.set_model(user.id, "")
                session.scratch.pop("model_profile", None)  # unpin now
            else:
                prefs.set_model(user.id, choice)
                session.scratch["model_profile"] = choice
            await _edit(callback, *_settings_ai(locale, user.id))
        elif action == "setlang":
            new_locale = normalize_locale(parts[2])
            prefs.set_language(user.id, new_locale)
            engine.session(session_id_for(user.id)).scratch["language"] = new_locale
            await _edit(callback, *_settings_prefs(new_locale, user.id))
        elif action in ("reset", "forget"):
            # Ask before wiping — these are destructive.
            await _edit(callback, *bm.screen_confirm(locale, action))
        elif action == "reset_do":
            await engine.reset(session_id_for(user.id))
            await _edit(callback, "🧹 " + t("reset_done", locale),
                        [[(t("menu_back", locale), "m:memory")]])
        elif action == "forget_do":
            await engine.forget(session_id_for(user.id))
            await _edit(callback, "🗑 " + t("forget_done", locale),
                        [[(t("menu_back", locale), "m:memory")]])
        elif action == "plans":
            await _show_plans(callback, *bm.screen_plans_hub(
                locale, plans, _user_plan(user.id).name))
        elif action == "plandetail":
            tier = parts[2]
            await _show_plans(callback, *bm.screen_plan_detail(
                locale, plans, _user_plan(user.id).name, tier))
        elif action == "buy":
            tier = parts[2] if len(parts) > 2 else None
            await _send_invoice(callback.message, locale, tier)

    async def _send_invoice(message: "Message", locale: str,
                            tier: str | None = None) -> None:
        if billing is None:
            await message.answer(t("buy_disabled", locale))
            return
        # A tiered purchase (plus/pro) carries the tier in the payload and uses
        # that tier's price; a bare purchase falls back to the default plan.
        if tier in plans and tier != "free":
            price = plans[tier].price_stars
            payload = f"jarvis-plan:{tier}"
            title = f"{settings.assistant_name} {t(f'plan_{tier}', locale)}"
        else:
            price = settings.billing_price_stars
            payload = "jarvis-license"
            title = t("buy_invoice_title", locale)
        from aiogram.types import LabeledPrice
        await message.bot.send_invoice(
            chat_id=message.chat.id,
            title=title,
            description=t("buy_invoice_desc", locale),
            payload=payload,
            currency="XTR",
            prices=[LabeledPrice(label=title, amount=price)],
        )

    @dp.callback_query(F.data.startswith("lang:"))
    async def _pick_language(callback: "CallbackQuery") -> None:
        locale = normalize_locale(callback.data.split(":", 1)[1])
        prefs.set_language(callback.from_user.id, locale)
        engine.session(session_id_for(callback.from_user.id)).scratch["language"] = locale
        await callback.answer()
        text, rows = _main_screen(callback.from_user.id, locale)
        try:
            await callback.message.edit_text(text, reply_markup=_markup(rows))
        except Exception:  # noqa: BLE001
            await callback.message.answer(text, reply_markup=_markup(rows))

    @dp.pre_checkout_query()
    async def _pre_checkout(query) -> None:
        await query.answer(ok=billing is not None)

    @dp.message(F.successful_payment)
    async def _paid(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if billing is None:
            return
        payment = message.successful_payment
        # A tiered invoice encodes the plan as "jarvis-plan:<tier>".
        plan_override = None
        payload = getattr(payment, "invoice_payload", "") or ""
        if payload.startswith("jarvis-plan:"):
            plan_override = payload.split(":", 1)[1]
        reply = handle_successful_payment(
            billing, settings, message.from_user.id,
            payment.telegram_payment_charge_id, locale,
            amount=payment.total_amount, currency=payment.currency,
            plan=plan_override,
        )
        await message.answer(reply)

    @dp.message(Command("link"))
    async def _link(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        reply = handle_link(license_service, message.text or "",
                            message.from_user.id, locale)
        await message.answer(reply)

    admins = settings.telegram_admins()

    @dp.message(F.text.startswith("/admin"))
    async def _admin(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if message.from_user.id not in admins:
            await message.answer(t("not_authorized", locale))
            return
        if license_service is None:
            await message.answer(t("admin_needs_auth", locale))
            return
        from jarvis.interfaces.admin_panel import handle_admin_command

        text = message.text or ""
        command = text.split(maxsplit=1)[0].split("@", 1)[0].lower()
        if command == "/admin_post":
            content = text.split(maxsplit=1)[1] if " " in text else ""
            if not content.strip():
                await message.answer(t("admin_post_usage", locale))
                return
            if not settings.telegram_channel:
                await message.answer(t("admin_no_channel", locale))
                return
            await message.bot.send_message(settings.telegram_channel,
                                        content, parse_mode=None)
            await message.answer(
                t("admin_posted", locale, channel=settings.telegram_channel))
            return
        reply = handle_admin_command(license_service, billing, text)
        await message.answer(reply if reply is not None
                            else t("admin_unknown", locale))

    @dp.message(F.text.startswith("/"))
    async def _stray_command(message: "Message") -> None:
        # The bot is fully button-driven: any leftover slash command (from an
        # old client menu or a habit) just re-opens the menu instead of being
        # treated as chat. /start, /link and the /admin* commands are matched
        # by their own handlers above, so they never reach here.
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        await _open_menu(message, message.from_user.id, locale)

    @dp.message(F.text)
    async def _chat(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        prefs.touch(message.from_user.id, message.chat.id)
        session = engine.session(session_id_for(message.from_user.id))
        # A pending support message is forwarded to the owner (before anything else).
        if session.scratch.pop("awaiting_support", False):
            await _send_support(message, locale)
            return
        # A pending "rename your assistant" message sets the per-user name.
        if session.scratch.pop("awaiting_assistant_name", False):
            new_name = (message.text or "").strip()[:32]
            if new_name:
                prefs.set_assistant_name(message.from_user.id, new_name)
                await message.answer(t("rename_done", locale, name=new_name))
            await _open_menu(message, message.from_user.id, locale)
            return
        # A pending marketplace search runs against the model registry.
        if session.scratch.pop("awaiting_market_search", False):
            import jarvis.interfaces.bot_menu as bm
            import jarvis.interfaces.model_registry as mr
            cards = mr.search(message.text)
            favs = [c.slug for c in favorites.list(message.from_user.id)]
            text, rows = bm.screen_market_list(
                locale, t("market_search", locale), cards,
                prefs.get_model_id(message.from_user.id) or "", favs)
            await message.answer(text, reply_markup=_markup(rows))
            return
        # "каждый день/каждые N часов …" → a recurring automation.
        from jarvis.interfaces.automations import is_automation
        if is_automation(message.text):
            await _handle_automation(message, locale)
            return
        # "напомни …" / "remind me …" → schedule a reminder.
        from jarvis.interfaces.reminders import is_reminder
        if is_reminder(message.text):
            await _handle_reminder(message, locale)
            return
        # An in-chat "api …" command (connect a key / search models).
        from jarvis.interfaces.chat_api import parse_api_command
        parsed = parse_api_command(message.text)
        if parsed is not None:
            await _handle_api_command(message, parsed, locale)
            return
        # A pending "connect your key" message is captured before any limit.
        awaiting_provider = session.scratch.pop("awaiting_byok", None)
        if awaiting_provider:
            await _save_byok(message, awaiting_provider, message.text, locale)
            return
        # A pending "connect an integration" message (URL | token).
        awaiting_int = session.scratch.pop("awaiting_integration", None)
        if awaiting_int:
            await _save_integration(message, awaiting_int, locale)
            return
        if not await _within_limit(message, message.from_user.id, locale):
            return
        # If the user tapped "Image", this message is a drawing prompt.
        if session.scratch.pop("awaiting_image", False):
            await _make_image(message, message.text, locale)
            return
        # Keep "typing…" alive for the whole (possibly tool-using) generation.
        reply, meta = await with_typing(message.bot, message.chat.id, generate_reply(
            engine, message.from_user.id, message.text, locale,
            model_profile=prefs.get_model(message.from_user.id),
            model_id=prefs.get_model_id(message.from_user.id),
            byok=prefs.get_byok(message.from_user.id),
            assistant_name=prefs.get_assistant_name(message.from_user.id),
            usage=usage,
            plan_images=_user_plan(message.from_user.id).images,
            return_metadata=True,
        ))
        # LLM output is plain text — disable HTML parsing to avoid entity errors.
        for chunk in split_message(reply):
            await message.answer(chunk, parse_mode=None)
        # The model may have called the generate_image tool mid-conversation
        # (no "Image" button needed — see jarvis/media/tools.py).
        image_b64 = meta.get("image_png_b64")
        if image_b64:
            import base64

            from aiogram.types import BufferedInputFile
            await message.answer_photo(
                BufferedInputFile(base64.b64decode(image_b64), "jarvis.png"))

    @dp.message(F.voice)
    async def _voice(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        if voice is None or not voice.stt_available():
            await message.answer(t("voice_unavailable", locale))
            return
        if not await _within_limit(message, message.from_user.id, locale):
            return
        prefs.touch(message.from_user.id, message.chat.id)

        await with_typing(message.bot, message.chat.id, _voice_pipeline(
            message, locale, usage))

    async def _voice_pipeline(message: "Message", locale: str, usage) -> None:
        """The STT → LLM → TTS round trip for one voice message, timed stage
        by stage (logged, not surfaced to the user) so a slow turn can be
        diagnosed instead of just felt.
        """
        from jarvis.utils.timing import measure

        try:
            with measure() as sw_stt:
                file = await message.bot.get_file(message.voice.file_id)
                buffer = await message.bot.download_file(file.file_path)
                transcription = await voice.transcribe(buffer.read())
        except Exception as exc:  # noqa: BLE001 - surface STT failures to the user
            logger.error("Voice transcription failed: %s", exc)
            await message.answer(t("error", locale, error=str(exc)), parse_mode=None)
            return
        logger.info("Voice: download+STT took %.0fms", sw_stt.elapsed_ms)

        if not transcription.text:
            return

        # Reply in whatever language the user actually spoke. source="voice"
        # gets a faster model / fewer tool-call rounds / a "keep it brief"
        # prompt hint from the engine — see JarvisEngine._ask_llm.
        with measure() as sw_llm:
            reply = await generate_reply(
                engine, message.from_user.id, transcription.text, locale,
                match_input_language=True,
                model_profile=prefs.get_model(message.from_user.id),
                model_id=prefs.get_model_id(message.from_user.id),
                byok=prefs.get_byok(message.from_user.id),
                assistant_name=prefs.get_assistant_name(message.from_user.id),
                usage=usage,
                source="voice",
            )
        logger.info("Voice: LLM reply took %.0fms", sw_llm.elapsed_ms)
        for chunk in split_message(reply):
            await message.answer(chunk, parse_mode=None)

        if settings.voice_replies and voice.tts_available():
            try:
                with measure() as sw_tts:
                    audio = await voice.synthesize(reply, transcription.language)
                logger.info("Voice: TTS took %.0fms", sw_tts.elapsed_ms)
                out = BufferedInputFile(audio, f"reply.{voice.tts_ext}")
                if voice.tts_is_voice_note:
                    await message.answer_voice(out)
                else:
                    await message.answer_audio(out)
            except Exception as exc:  # noqa: BLE001 - text reply already delivered
                logger.warning("Voice synthesis failed: %s", exc)

    async def _set_commands() -> None:
        # Fully button-driven — no user commands at all. Telegram caches the
        # blue "menu" button per client, and older deployments (or a manual
        # @BotFather /setcommands) may have populated it, so clear it
        # explicitly for every public scope, not just the default one.
        from aiogram.types import (
            BotCommandScopeAllGroupChats,
            BotCommandScopeAllPrivateChats,
            BotCommandScopeChat,
            BotCommandScopeDefault,
        )
        for scope in (BotCommandScopeDefault(),
                    BotCommandScopeAllPrivateChats(),
                    BotCommandScopeAllGroupChats()):
            try:
                await bot.delete_my_commands(scope=scope)
            except Exception as exc:  # noqa: BLE001 - non-fatal
                logger.debug("Clearing commands for %s failed: %s", scope, exc)

        # Admins additionally see the owner commands — only in their own chat.
        admin_extra = [
            BotCommand(command="admin", description=t("cmd_admin", DEFAULT_LOCALE)),
            BotCommand(command="admin_sales",
                    description=t("cmd_admin_sales", DEFAULT_LOCALE)),
        ]
        for admin_id in admins:
            try:
                await bot.set_my_commands(
                    admin_extra, scope=BotCommandScopeChat(chat_id=admin_id))
            except Exception as exc:  # noqa: BLE001 - admin hasn't /start-ed yet
                logger.debug("Admin menu for %s skipped: %s", admin_id, exc)

    async def _startup_report() -> None:
        """Log exactly what this process is running, so the deployed state is
        never a guess: version, whether the subscription gate is active, and —
        if it is — whether the bot can actually check membership."""
        nonlocal bot_username
        from jarvis import __version__
        try:
            me = await bot.get_me()
            bot_username = me.username or ""
            who = f"@{me.username}"
        except Exception as exc:  # noqa: BLE001
            who = f"<unknown: {exc}>"
        logger.info("%s bot %s starting as %s",
                    settings.assistant_name, __version__, who)
        # Active LLM configuration at a glance (which model actually runs).
        active_model = {
            "openrouter": settings.openrouter_model,
            "local": f"{settings.local_llm_backend}:{settings.local_llm_model}",
        }.get(settings.llm_provider, settings.llm_model)
        logger.info("LLM: provider=%s model=%s temp=%s max_tokens=%s",
                    settings.llm_provider, active_model,
                    settings.llm_temperature, settings.llm_max_tokens)
        logger.info("Mode: button-only (no user commands). "
                    "billing=%s auth=%s voice=%s images=%s",
                    billing is not None, license_service is not None,
                    voice is not None, image_service is not None)
        # Capability Manager: one line per feature (enabled/restricted/disabled).
        from jarvis.core.capabilities import CapabilityManager
        for line in CapabilityManager(settings).summary_lines():
            logger.info("CAPABILITY %s", line)
        # Configuration Manager: surface any misconfiguration up front.
        from jarvis.config.manager import ConfigManager
        for issue in ConfigManager(settings).validate():
            log = (logger.error if issue.level == "error"
                else logger.warning if issue.level == "warning"
                else logger.info)
            log("CONFIG %s", issue)
        # Security self-audit: highlight anything that widens the attack surface.
        from jarvis.security.audit import audit_settings
        for finding in audit_settings(settings):
            log = (logger.warning if finding.severity in ("high", "medium")
                else logger.info)
            log("SECURITY %s", finding)

        channel = settings.telegram_required_channel
        if not channel:
            logger.warning(
                "SUBSCRIPTION GATE: OFF — TELEGRAM_REQUIRED_CHANNEL is not set, "
                "so everyone can use the bot. Set it in .env (e.g. @your_channel) "
                "and make the bot an admin of that channel to enable the gate.")
            return
        logger.info("SUBSCRIPTION GATE: ON — required channel %s", channel)
        try:
            # If the bot isn't an admin of the channel, get_chat_member for
            # arbitrary users fails and the gate would block everyone — surface
            # that now instead of at first use.
            member = await bot.get_chat_member(channel, (await bot.get_me()).id)
            if member.status not in ("administrator", "creator"):
                logger.warning(
                    "SUBSCRIPTION GATE: the bot is NOT an admin of %s "
                    "(status=%s). Membership checks will fail and block users. "
                    "Add the bot as a channel admin.", channel, member.status)
            else:
                logger.info("SUBSCRIPTION GATE: verified — bot is admin of %s.",
                            channel)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "SUBSCRIPTION GATE: could not verify channel %s (%s). Ensure the "
                "channel exists and the bot is an admin of it.", channel, exc)

    async def _proactive_worker() -> None:
        """Background loop: fire due reminders and (opt-in) proactive nudges."""
        import time as _t
        from datetime import datetime
        sent_morning: dict[str, str] = {}   # user_id -> YYYY-MM-DD
        nudged: dict[str, float] = {}       # user_id -> last-nudge ts
        idle_seconds = settings.proactive_idle_days * 86400
        while True:
            try:
                now = _t.time()
                # 1) Fire any due reminders.
                for r in reminder_store.due(now):
                    loc = normalize_locale(prefs.get_language(r["user_id"]))
                    try:
                        await bot.send_message(
                            int(r["chat_id"]),
                            t("reminder_fire", loc, text=r["text"]),
                            parse_mode=None)
                    except Exception as exc:  # noqa: BLE001
                        logger.debug("Reminder send failed: %s", exc)
                    reminder_store.mark_fired(r["id"])
                # 1b) Run due automations: execute the task and deliver the
                #     result, then reschedule the next occurrence.
                from datetime import datetime as _dt

                from jarvis.interfaces.automations import next_run
                for a in automation_store.due(now):
                    loc = normalize_locale(prefs.get_language(a["user_id"]))
                    try:
                        reply = await generate_reply(
                            engine, int(a["user_id"]), a["prompt"], loc,
                            assistant_name=prefs.get_assistant_name(a["user_id"]))
                        await bot.send_message(
                            int(a["chat_id"]),
                            t("auto_fire", loc, prompt=a["prompt"][:60],
                            result=reply))
                    except Exception as exc:  # noqa: BLE001 - keep worker alive
                        logger.debug("Automation run failed: %s", exc)
                    spec = automation_store.spec_of(a)
                    automation_store.reschedule(a["id"], next_run(spec, _dt.now()))
                # 2) Morning check-in + idle nudge for opted-in users.
                hour = datetime.now().hour
                today = datetime.now().strftime("%Y-%m-%d")
                for row in prefs.list_proactive():
                    uid, chat_id = row["user_id"], row["chat_id"]
                    if not chat_id:
                        continue
                    loc = normalize_locale(row["language"])
                    if (hour == settings.proactive_morning_hour
                            and sent_morning.get(uid) != today):
                        sent_morning[uid] = today
                        try:
                            await bot.send_message(int(chat_id),
                                                t("morning_greeting", loc))
                        except Exception as exc:  # noqa: BLE001
                            logger.debug("Morning send failed: %s", exc)
                    elif (idle_seconds
                        and now - (row["last_seen"] or 0) > idle_seconds
                        and now - nudged.get(uid, 0) > idle_seconds):
                        nudged[uid] = now
                        try:
                            await bot.send_message(int(chat_id),
                                                t("idle_nudge", loc))
                        except Exception as exc:  # noqa: BLE001
                            logger.debug("Nudge send failed: %s", exc)
            except asyncio.CancelledError:
                raise
            except Exception as exc:  # noqa: BLE001 - keep the worker alive
                logger.warning("Proactive worker error: %s", exc)
            await asyncio.sleep(30)

    await _set_commands()
    await _startup_report()
    worker_task = asyncio.create_task(_proactive_worker())
    logger.info("Telegram bot starting (long-polling)…")
    try:
        # Keep the sales bot up 24/7: if polling dies (network drop, Telegram
        # hiccup), reconnect with exponential backoff instead of exiting.
        # aiogram already retries transient errors internally; this loop is
        # the belt-and-braces layer on top, and systemd/Docker restart the
        # whole process if even this fails.
        backoff = _POLL_BACKOFF_INITIAL
        while True:
            try:
                await dp.start_polling(bot)
                break  # clean stop (SIGINT/SIGTERM handled by aiogram)
            except asyncio.CancelledError:
                raise
            except Exception as exc:  # noqa: BLE001 - keep the bot alive
                logger.error("Polling crashed: %s — reconnecting in %.0fs",
                            exc, backoff)
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, _POLL_BACKOFF_MAX)
            else:  # pragma: no cover - defensive
                break
    finally:
        worker_task.cancel()
        try:
            await worker_task
        except (asyncio.CancelledError, Exception):  # noqa: BLE001
            pass
        await engine.shutdown()
        if license_service is not None:
            license_service.close()
        usage.close()
        referrals.close()
        reminder_store.close()
        automation_store.close()
        user_int_store.close()
        favorites.close()
        await bot.session.close()


def main() -> int:
    try:
        asyncio.run(run())
        return 0
    except ConfigError as exc:
        logger.error("%s", exc)
        return 1
    except KeyboardInterrupt:  # pragma: no cover
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
